replicaCount: 2
image:
  repository: ghcr.io/abrahimzaman360/elysia-app
  tag: 685b58b281b5fd411bbdc767000ba639d9f8a51f
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  port: 80
  targetPort: 3000
  type: LoadBalancer
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
ingress:
  enabled: true
  path: /elysia
  pathType: Prefix
  ingressClassName: nginx
  annotations: {}
