replicaCount: 2
image:
  repository: ghcr.io/abrahimzaman360/elysia-app
  tag: 871a17a5a035c6715780a4e243f8373bd6e9ff87
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  port: 80
  targetPort: 3000
  type: LoadBalancer
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
ingress:
  enabled: true
  path: /elysia
  pathType: Prefix
  ingressClassName: nginx
  annotations: {}
