replicaCount: 2
image:
  repository: ghcr.io/abrahimzaman360/elysia-app
  tag: 561fb4b3b553a89c803444e8157ca3c6d77348ea
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  port: 3000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
ingress:
  enabled: true
  path: /elysia
  pathType: Prefix
  ingressClassName: nginx
  annotations: {}
