replicaCount: 2

image:
  repository: elysia-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

ingress:
  enabled: true
  path: /elysia(/|$)(.*)
  pathType: Prefix
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
