replicaCount: 2
image:
  repository: ghcr.io/abrahimzaman360/elysia-app
  tag: cbf099ae8ef7dd33d75a3c14414484636c1a3aa2
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret
service:
  port: 3000
  targetPort: 3000
  type: ClusterIP
  nodePort: 3000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
ingress:
  enabled: true
  path: /elysia
  pathType: Prefix
  ingressClassName: nginx
  annotations: {}
