apiVersion: v1
kind: Service
metadata:
  name: elysia-app-svc
spec:
  selector:
    app: { { include "elysia-app.name" . } }
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
