apiVersion: v1
kind: Service
metadata:
   name: {{ include "elysia-app.fullname" . }}-svc
  labels:
    app: { { include "elysia-app.name" . } } # Helm label to match Deployment
spec:
  selector:
    app: { { include "elysia-app.name" . } } # Make sure this matches Deployment labels
  type: ClusterIP # ✅ Use internal-only service
  ports:
    - protocol: TCP
      port: 80 # NGINX will talk to this port
      targetPort: 3000 # Elysia app container port
