apiVersion: v1
kind: Service
metadata:
  name: {{ include "elysia-app.fullname" . }}
  labels:
    app: {{ include "elysia-app.name" . }}
spec:
  selector:
    app: {{ include "elysia-app.name" . }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}