name: Build & Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Docker
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # ✅ Build and push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      # ✅ Set up KUBECONFIG
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        shell: bash

      # ✅ Deploy to Kubernetes using kubectl or helm
      - name: Deploy to K8s
        run: |
          kubectl apply -f ./kubernetes
          # OR:
          # helm upgrade --install elysia-app ./helm/elysia-app --namespace default --create-namespace
